name: docker build and push
description: builds and pushes a docker image to docker hub
inputs:
  DOCKERHUB_USERNAME:
    required: true
  DOCKERHUB_PASSWORD:
    required: true
  dockerfile-path:
    required: false
    description: uses root dir if not specified
  image-name:
    required: true
  build-args:
    required: false
  registry:
    required: false
outputs:
  imageid:
    value: ${{ steps.build-and-push.outputs.imageid }}
runs:
  using: "composite"
  steps:
    -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ inputs.image-name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_PASSWORD }}
        registry: ${{ inputs.registry }}
    - name: set environment variable for dockerfile path
      run: |
        if [[ "${{ inputs.dockerfile-path }}" == "" ]]; then
          echo "DOCKERFILE_PATH=." >> $GITHUB_ENV
        else
          echo "DOCKERFILE_PATH=${{ inputs.dockerfile-path  }}" >> $GITHUB_ENV
        fi
        if [[ "${{ inputs.registry }}" == "" ]]; then
          echo "REGISTRY=" >> $GITHUB_ENV
        else
          echo "REGISTRY=${{ inputs.registry }}/" >> $GITHUB_ENV
        fi
      shell: bash
    - name: set environment variable for build args
      run: |
        echo ${{ inputs.build-args }} | tr -s ',' '\n' > build-args.txt
        echo 'BUILD_ARGS<<EOF' >> $GITHUB_ENV
        cat build-args.txt >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV 
      shell: bash
    - name: Build and push
      id: build-and-push
      uses: docker/build-push-action@v3
      with:
        context: ${{ env.DOCKERFILE_PATH }}
        push: true
        build-args: |
          ${{ env.BUILD_ARGS }}
        tags: ${{ env.REGISTRY }}${{ inputs.DOCKERHUB_USERNAME }}/${{ steps.meta.outputs.tags }}
