name: Terraform sentinel policies check

on:
  workflow_call:
    secrets:
      TF_TOKEN:
        required: true
      ORGANIZATION:
        required: true

jobs:
  format:
    runs-on: ubuntu-latest
    name: sentinel check
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        id: validate
        with:
          path: .

      - name: Validate failed
        if: ${{ failure() && steps.validate.outputs.failure-reason == 'validate-failed' }}
        run: echo "terraform validate failed"
    
      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
        with:
          path: .
      
      - name: checkout terraform code
        uses: actions/checkout@v2
        with:
          repository: temp-org274/repoA
          path: ./config-code
      - name: run docker container containing script
        uses: addnab/docker-run-action@v3
        with:
          image: sentinel:0.1.2
          options: -v ./config-code:/opt/sentinel/config-code ${{ secrets.TF_TOKEN }} ${{ secrets.ORGANIZATION }} ${{ github.event.repository.name }}
      - name: debugging
        run: |
          ls
          # echo "MESSAGE=$(cat message.txt)" >> $GITHUB_ENV
          
          echo 'MESSAGE_ENV<<EOF' >> $GITHUB_ENV
          cat message.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: write policy check result to pr
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            ${{ env.MESSAGE_ENV }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

