name: Terraform sentinel policies check

on:
  workflow_call:
    secrets:
      TF_TOKEN:
        required: true
      ORGANIZATION:
        required: true

jobs:
  format:
    runs-on: ubuntu-latest
    name: sentinel check
    env:
      MESSAGE: default-message
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        id: validate
        with:
          path: .

      - name: Validate failed
        if: ${{ failure() && steps.validate.outputs.failure-reason == 'validate-failed' }}
        run: echo "terraform validate failed"
    
      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
        with:
          path: .
      - name: checkout script and policies
        uses: actions/checkout@v2
        with:
          repository: temp-org274/repoA
          path: ./temp_path
      - name: github context
        run: |
          ls
          mv ./temp_path/* .
          rm -rf temp_path
          echo
          ls

      - name: execute script
        run: bash script.sh ${{ secrets.TF_TOKEN }} ${{ secrets.ORGANIZATION }} ${{ github.event.repository.name }}
      - name: debugging
        run: |
          ls
          echo "$(cat message.txt)" >> "$MESSAGE"
      - name: write policy check result to pr
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            ${{ env.MESSAGE }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

