name: Terraform formating and validation

on:
  workflow_call:
    secrets:
      TF_TOKEN:
        required: true
      ORGANIZATION:
        required: true

jobs:
  format:
    runs-on: ubuntu-latest
    name: Terraform fmt
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        id: validate
        with:
          path: .

      - name: Validate failed
        if: ${{ failure() && steps.validate.outputs.failure-reason == 'validate-failed' }}
        run: echo "terraform validate failed"
    
      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
        with:
          path: .
      - name: checkout script and policies
        uses: actions/checkout@v2
        with:
          repository: temp-org274/repoA
          path: ./temp_path
      - name: github context
        run: |
          echo ${{ github.action_repository }}
          echo ${{ github.action_path }}
          ls
          mv ./temp_path/* .
          echo
          ls
          echo ${{ secrets.TF_TOKEN }}
          echo ${{ secrets.ORGANIZATION }}
          echo ${{ github.event.repository.name }}
      - name: execute script
        run: bash script.sh ${{ secrets.TF_TOKEN }} ${{ secrets.ORGANIZATION }} ${{ github.event.repository.name }}
