name: Terraform sentinel policies check

on:
  workflow_call:
    inputs:
      varset:
        type: string
    secrets:
      TF_TOKEN:
        required: true
      ORGANIZATION:
        required: true
      GIT_TOKEN:
        required: true

jobs:
  format:
    runs-on: ubuntu-latest
    name: sentinel check
    env:
      currentDir: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}
    steps:
      - name: checkout terraform code
        uses: actions/checkout@v3
        with:
          path: ./config-code
      - name: checkout sentinel policies
        uses: actions/checkout@v3
        with:
          repository: infracloudio/sentinel-policy-as-code
          token: ${{ secrets.GIT_TOKEN }}
          path: ./sentinel-policy-as-code
      - name: run docker container containing script
        uses: addnab/docker-run-action@v3
        with:
          image: ruchabhange/sentinel:0.1.0
          options: -v ${{ env.currentDir }}/sentinel-policy-as-code/common-functions:/opt/sentinel/common-functions -v ${{ env.currentDir }}/sentinel-policy-as-code/policies:/opt/sentinel/policies  -v ${{ env.CurrentDir }}/config-code:/opt/sentinel/config-code -e TF_TOKEN=${{ secrets.TF_TOKEN }} -e organization=${{ secrets.ORGANIZATION }} -e workspace=${{ github.event.repository.name }} -e varset=${{ inputs.varset }}
          shell: bash
          run: /opt/sentinel/script.sh
