name: Terraform sentinel policies check

on:
  workflow_call:
    inputs:
      varset:
        type: string
    secrets:
      TF_TOKEN:
        required: true
      ORGANIZATION:
        required: true
      PRIVATE_SSH_KEY:
        required: true

jobs:
  format:
    runs-on: ubuntu-latest
    name: sentinel check
    env:
      currentDir: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}
    steps:
      - name: checkout terraform code
        uses: actions/checkout@v3
        with:
          path: ./config-code
      - name: checkout sentinel policies
        uses: actions/checkout@v3
        with:
          repository: temp-org274/sentinel-policy-as-code
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          path: ./sentinel-policy-as-code
      - name: run docker container containing script
        uses: addnab/docker-run-action@v3
        with:
          image: ruchabhange/sentinel:0.1.0
          options: -v ${{ env.currentDir }}/sentinel-policy-as-code/common-functions:/opt/sentinel/common-functions -v ${{ env.currentDir }}/sentinel-policy-as-code/policies:/opt/sentinel/policies  -v ${{ env.currentDir }}/config-code:/opt/sentinel/config-code -e TF_TOKEN=${{ secrets.TF_TOKEN }} -e organization=${{ secrets.ORGANIZATION }} -e workspace=${{ github.event.repository.name }} -e varset=${{ inputs.varset }}
          shell: bash
          run: /opt/sentinel/script.sh
      - run: |
          echo 'MESSAGE_ENV<<EOF' >> $GITHUB_ENV
          cat ${{ env.currentDir }}/policies/message.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: write policy check result to pr
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            ${{ env.MESSAGE_ENV }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

