name: Terraform sentinel policies check

on:
  workflow_call:
    secrets:
      TF_TOKEN:
        required: true
      ORGANIZATION:
        required: true

jobs:
  format:
    runs-on: ubuntu-latest
    name: sentinel check
    steps:
      - name: checkout terraform code
        uses: actions/checkout@v2
      - name: debug
        run: |
          pwd
          ls ~
          
      - name: run docker container containing script
        uses: addnab/docker-run-action@v3
        with:
          image: ruchabhange/sentinel:0.1.2
          options: -v /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/opt/sentinel/config-code -e TF_TOKEN=${{ secrets.TF_TOKEN }} -e organization=${{ secrets.ORGANIZATION }} -e workspace=${{ github.event.repository.name }}
          shell: bash
          run: /opt/sentinel/script.sh
